FROM gcr.io/kubeflow-images-public/ingress-setup:latest
FROM gcr.io/kubeflow-images-public/admission-webhook:v1.0.0-gaf96e4e3
FROM gcr.io/kubeflow-images-public/centraldashboard:v1.0.0-g3ec0de71
FROM gcr.io/kubeflow-images-public/jupyter-web-app:v1.0.0-g2bd63238
FROM gcr.io/kubeflow-images-public/notebook-controller:v1.0.0-gcd65ce25
FROM gcr.io/kubeflow-images-public/profile-controller:v1.0.0-g34aa47c2
FROM gcr.io/kubeflow-images-public/kfam:v1.0.0-gf3e09203
FROM gcr.io/kubeflow-images-public/pytorch-operator:v1.0.0-g047cf0f
FROM gcr.io/kubeflow-images-public/tf_operator:v1.0.0-g92389064
FROM gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:v0.8.0
FROM gcr.io/kubeflow-images-public/katib/v1alpha3/katib-db-manager:v0.8.0
FROM gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui:v0.8.0
FROM gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta
FROM gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
FROM gcr.io/kfserving/kfserving-controller:0.2.2
FROM gcr.io/kubeflow-images-public/metadata:v0.1.11
FROM gcr.io/ml-pipeline/envoy:metadata-grpc
FROM gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1
FROM gcr.io/kubeflow-images-public/metadata-frontend:v0.1.8
FROM gcr.io/ml-pipeline/api-server:0.2.0
FROM gcr.io/ml-pipeline/visualization-server:0.2.0
FROM gcr.io/ml-pipeline/persistenceagent:0.2.0
FROM gcr.io/ml-pipeline/scheduledworkflow:0.2.0
FROM gcr.io/ml-pipeline/frontend:0.2.0
FROM gcr.io/ml-pipeline/viewer-crd-controller:0.2.0
FROM gcr.io/spark-operator/spark-operator:v1beta2-1.0.0-2.4.4
FROM gcr.io/google_containers/spartakus-amd64:v1.1.0